require("./bootstrap");
require("./paymentsReview");
require("./studentFinalAccepted");
require("./studentForm");
require("./excelForm");
require("./deptBoss");
require("./studentCourses");
require("./publishToRayat");
import Swal from "sweetalert2";
window.Swal = Swal;
