require("./bootstrap");
require("./studentsDocumentsReview");
require("./studentFinalAccepted");
require("./studentForm");
require("./excelForm");
require("./deptBoss");
require("./falteringStudents");
require("./publishToRayat");
import Swal from "sweetalert2";
window.Swal = Swal;
